name: 'dbt_basket_craft'
version: '1.0.0'

profile: 'dbt_basket_craft'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dbt_basket_craft:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +schema: staging
      +materialized: view
    warehouse:
      +schema: warehouse
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
